### PR TITLE
minor changes to introductory text

### PR DESCRIPTION
**Pull request by sjgraves**

### CODE REVIEW

**Comment by sjgraves** [comment]
hey @mkamenet3 - could you check that I did this right and merge?

**Comment by mkamenet3** [comment]
@sstevens2 @sjgraves  Content looks great, but I'm not sure why Travis is failing (dang it, Travis!). Something about `remotes`, but I don't think any of the text changes should have affected this?

**Comment by sstevens2** [comment]
Hmm... it might not be set up to run the checks right on PRs? When you are ready to merge please do so and if it still fails after it merges, I'll take a look at it again to try to fix.

**Comment by sstevens2** [comment]
The good news is the old version of the site will stay up even if this fails..the bad would be that it wouldn't update with any new changes until I fix it.

**Comment by mkamenet3** [comment]
Changes looked good, crossing fingers now.

**Comment by sstevens2** [comment]
🤞

**Comment by sstevens2** [comment]
yay it built!

**Pull request merged**
